name: Gold & Silver Sniper Bot

on:
  workflow_dispatch:

jobs:
  run-sniper:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy ta python-telegram-bot==20.4

      - name: Run Sniper Bot
        run: |
          python sniper_bot.py
