name: Run Deriv Sniper Bot

on:
  schedule:
    # Run every 5 hours
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      DERIV_API_KEY: ${{ secrets.DERIV_API_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy requests websocket-client

      - name: Run Deriv Sniper Bot
        run: |
          python deriv_bot.py
